.TH CERT_RECEIVE.PY "8" "June 2022" "cert_receive.py 0.1" "System Manager's Manual"
.SH NAME
cert_receive.py \- install SSL/TLS certificates
.SH DESCRIPTION
usage: cert_receive.py [\-h] [\-\-ca\-file CA_FILE] [\-\-ca\-path CA_PATH]
.TP
[\-\-no\-ca\-path] [\-\-check\-config]
.TP
[\-\-config\-file CONFIG_FILE]
.TP
[\-\-receive\-timeout RECEIVE_TIMEOUT]
.TP
[\-\-set\-effective\-user SET_EFFECTIVE_USER]
.TP
[\-\-no\-set\-effective\-user]
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.HP
\fB\-\-ca\-file\fR CA_FILE
.HP
\fB\-\-ca\-path\fR CA_PATH
.HP
\fB\-\-no\-ca\-path\fR
.HP
\fB\-\-check\-config\fR
.HP
\fB\-\-config\-file\fR CONFIG_FILE
.HP
\fB\-\-receive\-timeout\fR RECEIVE_TIMEOUT
.HP
\fB\-\-set\-effective\-user\fR SET_EFFECTIVE_USER
.HP
\fB\-\-no\-set\-effective\-user\fR
