.TH CERTBOT_SEND.SH "8" "January 2026" "certbot_send.sh 0.3" "System Manager's Manual"
.
.\" Copyright (C) 2022, 2025, 2026 Keith Allen Bare II
.
.\" This file is part of cert-propagation.
.\"
.\" cert-propagation is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by the
.\" Free Software Foundation, either version 3 of the License, or (at your
.\" option) any later version.
.\"
.\" cert-propagation is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
.\" Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with cert-propagation. If not, see <https://www.gnu.org/licenses/>.
.
.\" compatibility shim for groff < 1.23 and older man(7) lacking .MR support
.if !dMR \{\
.  de MR
.    I \\$1(\\$2)
..
.\}
.
.SH NAME
certbot_send.sh \- send TLS/SSL certificates and keys to remote hosts
.
.\" ========================================================================
.SH SYNOPSIS
.\" ========================================================================
.SY \%env\~RENEWED_LINEAGE=\fR.\|.\|./\fP\:live/\:\fIconfig_name\fP\~\e
.SY \%certbot_send.sh
.RB \%[ \-\-config\-dir \~\fIDIR\fP]
.
.RB \%[ \-\-config\-file \~\fIFILE\fP]
.
.RB \%[ \-\-defaults\-file \~\fIFILE\fP\~|\~ \-\-no\-defaults\-file ]
.
.RB \%[ \-\-dry\-run ]
.YS
.
.SY \%certbot_send.sh\~\-\-help
.YS
.SY \%certbot_send.sh\~\-\-version
.YS
.
.\" ========================================================================
.SH DESCRIPTION
.\" ========================================================================
The
.I \%certbot_send.sh
script sends TLS certificates and private keys to one or more recipient
hosts using
.MR ssh 1
and presents the data in the format expected by
.MR cert_receive.py 8 .
The recipient hosts and parameters of the
.I ssh
command can be configured by files in the script's configuration directory,
\%\(lq/etc/\:certbot_send\(rq by default.  The script is designed to work as
a
.MR certbot 1
deploy hook.
.
.\" ========================================================================
.SH OPTIONS
.\" ========================================================================
.TP
.BI \%\-\-config\-dir\~ DIR
Search for configuration files in
.IR DIR ;
defaults to \%\(lq/etc/\:certbot_send\(rq
.
.TP
.BI \%\-\-config\-file\~ FILE
Read variable settings indicating how to handle
.I \%config_name
from
.IR FILE ;
defaults to
.RI \%\(lq config_dir / config_name .conf\(rq
.
.TP
.BI \%\-\-defaults\-file\~ FILE
.TQ
.B \%\-\-no\-defaults\-file
Read default variable settings applicable to all or most configurations from
.IR FILE ;
defaults to
.RI \%\(lq config_dir /defaults\(rq
unless
.B \%\-\-no\-defaults\-file
is specified, which prevents use of any defaults file
.
.TP
.BR \%\-\-dry\-run\~ ( \-n )
Show the commands that would be executed, instead of actually executing them
.
.TP
.BR \%\-\-help\~ ( \-h )
Display a short usage synopsis and exit
.
.TP
.BR \%\-\-version\~ ( \-V )
Display the script version and copying information then exit
.
.\" ========================================================================
.SH FILES
.\" ========================================================================
.TP
\%/etc/\:certbot_send
default configuration directory
.TP
.IR \%config_dir /\: config_name .conf
default configuration file for
.I \%config_name
.
.TP
.IR \%config_dir /\:defaults
default defaults file
.
.TP
.IR \%config_dir /\:ssh_config
default
.MR ssh_config 5
used by
.I ssh
invocations, if present
.
.\" ========================================================================
.SH ENVIRONMENT
.\" ========================================================================
.TP
RENEWED_LINEAGE
The path to
.IR \%certbot 's
\(lqlive\(rq directory for the certificate(s) and key to be sent
.
.\" ========================================================================
.SH SEE ALSO
.\" ========================================================================
.MR certbot_send 5 ,
.MR certbot 1 ,
.MR cert_receive.py 8
